<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0</name>
   <tag></tag>
   <elementGuidId>4e10d737-6402-49a6-8af6-6f732fb44496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.et_pb_sum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-5050']/div/div/div/div/div[2]/div/div/div/div/div[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$0&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0e92579d-af49-49c4-b170-b79f3215157b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_sum</value>
      <webElementGuid>5a7be0a6-e3fa-4cb0-b8b7-5e470eb15add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$0</value>
      <webElementGuid>3e6424f5-341e-4cc3-9358-8860dd681b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-5050&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters3&quot;]/div[@class=&quot;et_pb_section et_pb_section_0 et_animated et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_1 et_pb_gutters2&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_3 et_pb_column_1  et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_with_border et_pb_module et_pb_pricing_tables_0 et_pb_pricing clearfix et_pb_pricing_1 et_pb_no_featured_in_first_row et_pb_pricing_no_bullet&quot;]/div[@class=&quot;et_pb_pricing_table_wrap&quot;]/div[@class=&quot;et_pb_pricing_table et_pb_pricing_table_0 et_hover_enabled&quot;]/div[@class=&quot;et_pb_pricing_content_top&quot;]/span[@class=&quot;et_pb_et_price&quot;]/span[@class=&quot;et_pb_sum&quot;]</value>
      <webElementGuid>e421757d-4e94-49ba-89ae-a7a7d067e079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-5050']/div/div/div/div/div[2]/div/div/div/div/div[2]/span/span</value>
      <webElementGuid>842475ea-72b0-46e2-ac57-851e26fb2144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Trial'])[1]/following::span[2]</value>
      <webElementGuid>bf57364e-2399-4e29-841f-4e30e11f113d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick a Plan that Works for Your Business Model'])[1]/following::span[2]</value>
      <webElementGuid>374e193a-2b00-410d-9070-17625d7a2183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::span[1]</value>
      <webElementGuid>77da8d52-f8d3-4835-bac3-bf000ab3aec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$0']/parent::*</value>
      <webElementGuid>176c8f2d-37a7-4e5b-90ed-d029d1740eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>7621c3ac-c3da-4ca0-8cc6-2b587af2c9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$0' or . = '$0')]</value>
      <webElementGuid>b3e9d50d-3a79-4645-8d6f-6dbe4f9349f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
