<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_900</name>
   <tag></tag>
   <elementGuidId>b1d0e170-0541-4387-b63e-fe0c407870df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.et_pb_pricing_table.et_pb_pricing_table_2.et_hover_enabled > div.et_pb_pricing_content_top > span.et_pb_et_price > span.et_pb_sum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-5050']/div/div/div/div/div[2]/div[3]/div/div/div/div[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$900&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f53f7bd-2211-41eb-8176-f11a07b11469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_sum</value>
      <webElementGuid>494073d3-5887-4d85-b42d-53f48e5e36e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$900</value>
      <webElementGuid>7a6cbe59-14bf-41a7-85fa-b9adf9bc86fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-5050&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters3&quot;]/div[@class=&quot;et_pb_section et_pb_section_0 et_animated et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_1 et_pb_gutters2&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_3 et_pb_column_3  et_pb_css_mix_blend_mode_passthrough et-last-child&quot;]/div[@class=&quot;et_pb_with_border et_pb_module et_pb_pricing_tables_2 et_pb_pricing clearfix et_pb_pricing_1 et_pb_no_featured_in_first_row et_pb_pricing_no_bullet&quot;]/div[@class=&quot;et_pb_pricing_table_wrap&quot;]/div[@class=&quot;et_pb_pricing_table et_pb_pricing_table_2 et_hover_enabled&quot;]/div[@class=&quot;et_pb_pricing_content_top&quot;]/span[@class=&quot;et_pb_et_price&quot;]/span[@class=&quot;et_pb_sum&quot;]</value>
      <webElementGuid>8eae48d9-ab54-4542-b055-b50cca0437a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-5050']/div/div/div/div/div[2]/div[3]/div/div/div/div[2]/span/span</value>
      <webElementGuid>370f13bd-94ee-4964-b12d-37199d6f705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise'])[1]/following::span[2]</value>
      <webElementGuid>9fb7679c-470d-4216-bccc-8a822bcd57ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase'])[2]/following::span[2]</value>
      <webElementGuid>860ca7bb-0ebc-478c-ad4b-887b2dba37da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[3]/preceding::span[1]</value>
      <webElementGuid>78002732-e514-48de-a337-3626a02e5032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$900']/parent::*</value>
      <webElementGuid>212866c2-93b7-4d7f-93c6-a2bcaa503add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/span/span</value>
      <webElementGuid>032b219b-4f59-4605-84e2-9d69c3b77719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$900' or . = '$900')]</value>
      <webElementGuid>4be84541-0c0e-4ba6-83a4-ff667549ace2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
