<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_80</name>
   <tag></tag>
   <elementGuidId>0c082fee-b982-46c9-ad16-3204b1665675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.et_pb_pricing_table.et_pb_pricing_table_1.et_hover_enabled > div.et_pb_pricing_content_top > span.et_pb_et_price > span.et_pb_sum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-5050']/div/div/div/div/div[2]/div[2]/div/div/div/div[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$80&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0511144e-3ea2-4345-9d5f-5f846d9b1e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_sum</value>
      <webElementGuid>d5c0fd29-240a-4bd1-828c-11c34be94c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$80</value>
      <webElementGuid>68542341-823c-4abf-8de6-c729b49c0d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-5050&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;et-l et-l--post&quot;]/div[@class=&quot;et_builder_inner_content et_pb_gutters3&quot;]/div[@class=&quot;et_pb_section et_pb_section_0 et_animated et_pb_with_background et_section_regular&quot;]/div[@class=&quot;et_pb_row et_pb_row_1 et_pb_gutters2&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_3 et_pb_column_2  et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_with_border et_pb_module et_pb_pricing_tables_1 et_pb_pricing clearfix et_pb_pricing_1 et_pb_no_featured_in_first_row et_pb_pricing_no_bullet&quot;]/div[@class=&quot;et_pb_pricing_table_wrap&quot;]/div[@class=&quot;et_pb_pricing_table et_pb_pricing_table_1 et_hover_enabled&quot;]/div[@class=&quot;et_pb_pricing_content_top&quot;]/span[@class=&quot;et_pb_et_price&quot;]/span[@class=&quot;et_pb_sum&quot;]</value>
      <webElementGuid>848ca5b9-b37d-421b-a989-3203124f5452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-5050']/div/div/div/div/div[2]/div[2]/div/div/div/div[2]/span/span</value>
      <webElementGuid>98f6bf24-bd68-40d7-90f7-ba86fde69d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[1]/following::span[2]</value>
      <webElementGuid>5052ed2d-3d2e-45d3-8d18-41f0f6031f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase'])[1]/following::span[2]</value>
      <webElementGuid>2cbd5c36-5ed6-4219-827a-89264dbf3a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/preceding::span[1]</value>
      <webElementGuid>a76f8291-2ed6-4644-b916-1c0f9a08197e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$80']/parent::*</value>
      <webElementGuid>b3129d7b-fd16-49b7-8eb2-4537579c0cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span/span</value>
      <webElementGuid>f3078ad0-b3c8-4ef4-860a-ee3c769d6ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$80' or . = '$80')]</value>
      <webElementGuid>6c212688-6aac-4264-9b02-77438203375b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
