<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Broken Images_wp-image-4398 sp-no-webp</name>
   <tag></tag>
   <elementGuidId>1cd9285c-6aa9-475f-add2-9db6cfecc1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-1218']/div/div/div/div/figure/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-4398.sp-no-webp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;JavaScript Logo | JavaScript Language Logo | JavaScript&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28b8cd27-f2e5-47ec-8881-f0e87c3cf9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i0.wp.com/practice-automation.com/wp-content/uploads/2022/02/javascript-logo.jpg?resize=169%2C169&amp;ssl=1</value>
      <webElementGuid>7d0adc65-d481-431d-a370-2d5c868931c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>169</value>
      <webElementGuid>0db54f18-0eb3-4355-aed0-bf88458184a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>169</value>
      <webElementGuid>cb671095-a811-4908-bf9d-9e4550c7b5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://i0.wp.com/practice-automation.com/wp-content/uploads/2022/02/javascript-logo.jpg?w=169&amp;ssl=1 169w, https://i0.wp.com/practice-automation.com/wp-content/uploads/2022/02/javascript-logo.jpg?resize=150%2C150&amp;ssl=1 150w</value>
      <webElementGuid>01b3b80d-0e5d-446b-9861-0c4b68460fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 169px) 100vw, 169px</value>
      <webElementGuid>42fbe48c-5a97-488b-a402-6ea13f8a48c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-4398 sp-no-webp</value>
      <webElementGuid>b91e4e8c-f6bb-4441-bca0-668d8b534885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>JavaScript Logo | JavaScript Language Logo | JavaScript</value>
      <webElementGuid>725bfcb4-bde7-47eb-893e-b29d5006e0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ec9315bb-42f9-4f69-b217-b60d5e5fc72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attachment-id</name>
      <type>Main</type>
      <value>4398</value>
      <webElementGuid>5d6f11f0-4afd-41f8-b2a8-5ee836666a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-permalink</name>
      <type>Main</type>
      <value>https://practice-automation.com/javascript-logo/</value>
      <webElementGuid>6909e75b-0edf-4ba0-b4ae-f585e333b8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-file</name>
      <type>Main</type>
      <value>https://i0.wp.com/practice-automation.com/wp-content/uploads/2022/02/javascript-logo.jpg?fit=169%2C169&amp;ssl=1</value>
      <webElementGuid>27669f62-258b-4d42-a915-8522a2ab4e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orig-size</name>
      <type>Main</type>
      <value>169,169</value>
      <webElementGuid>eebd2d3c-cf2d-44b0-8144-fe09ae9a5e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-comments-opened</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6a244414-f560-4ba1-98ef-b99b97472a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-meta</name>
      <type>Main</type>
      <value>{</value>
      <webElementGuid>ca5499af-c85c-4d0a-ac07-e41eceda5f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-title</name>
      <type>Main</type>
      <value>javascript-logo</value>
      <webElementGuid>57a7fb60-6823-48de-a8c7-ba2854bff0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium-file</name>
      <type>Main</type>
      <value>https://i0.wp.com/practice-automation.com/wp-content/uploads/2022/02/javascript-logo.jpg?fit=169%2C169&amp;ssl=1</value>
      <webElementGuid>52695ff1-fa03-4a01-be9b-5dc5b6aa0058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large-file</name>
      <type>Main</type>
      <value>https://i0.wp.com/practice-automation.com/wp-content/uploads/2022/02/javascript-logo.jpg?fit=169%2C169&amp;ssl=1</value>
      <webElementGuid>4b08bcca-08c2-4aca-9aa0-d2338896c10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b1eefc5-002c-4402-afa3-c80606f9666b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92481136-09eb-47a6-8218-676ba3405ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recalc-dims</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8ce55907-c5b3-4ad8-ba06-04efebd3b2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1218&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;wp-block-group is-layout-flow wp-block-group-is-layout-flow&quot;]/div[@class=&quot;wp-block-columns is-layout-flex wp-container-core-columns-is-layout-1 wp-block-columns-is-layout-flex&quot;]/div[@class=&quot;wp-block-column is-layout-flow wp-block-column-is-layout-flow&quot;]/figure[@class=&quot;wp-block-image size-full&quot;]/picture[1]/img[@class=&quot;wp-image-4398 sp-no-webp&quot;]</value>
      <webElementGuid>e2a904eb-d8f0-485f-9ee4-d2505f4211a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1218']/div/div/div/div/figure/picture/img</value>
      <webElementGuid>f4b1592d-d3ea-4a95-a689-0b786312c1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='JavaScript Logo | JavaScript Language Logo | JavaScript']</value>
      <webElementGuid>0de02e47-fe97-4f52-81f9-07eb845b7a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>719f163d-5083-4118-86b6-f6bd0f6dfef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i0.wp.com/practice-automation.com/wp-content/uploads/2022/02/javascript-logo.jpg?resize=169%2C169&amp;ssl=1' and @alt = 'JavaScript Logo | JavaScript Language Logo | JavaScript']</value>
      <webElementGuid>e80d5b18-0434-4d74-8484-3873c3739345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
