<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_19.2725899</name>
   <tag></tag>
   <elementGuidId>359f8300-4cf3-4593-b872-ffb83af18be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lat-value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lat-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;19.2725899&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a579bcd5-a000-439d-ac93-be0523e669ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lat-value</value>
      <webElementGuid>2da962f3-f9e8-465e-b38c-627ffdf01483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19.2725899</value>
      <webElementGuid>534b7491-3233-4688-b819-64bf72b17f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lat-value&quot;)</value>
      <webElementGuid>93b3bf7f-686d-4820-89d9-285b440880aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='lat-value']</value>
      <webElementGuid>cbfcddb5-6ac9-40e3-b306-10c4178346aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='geoInfo']/div</value>
      <webElementGuid>75b4b2bb-5cce-40d6-98ec-7dd0fee4637d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geolocation page for Automation Testing Practice'])[2]/following::div[1]</value>
      <webElementGuid>19f34bde-dd27-439c-b108-9567d7be8650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geolocation'])[1]/following::div[1]</value>
      <webElementGuid>90d09495-fd95-45be-b16a-cdc696c17afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See it on Google'])[1]/preceding::div[2]</value>
      <webElementGuid>bf22c512-2da0-4062-8962-c1e2f5f3bbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where am I?'])[1]/preceding::div[3]</value>
      <webElementGuid>32aee948-6c31-4f82-94a7-e08c6c5dd7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19.2725899']/parent::*</value>
      <webElementGuid>09de5d00-d975-4c7d-af48-91d7a594646a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/div</value>
      <webElementGuid>9ccbde30-3f6e-4486-bfc9-b612b7b2a3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'lat-value' and (text() = '19.2725899' or . = '19.2725899')]</value>
      <webElementGuid>ee35a787-1b71-4b04-8342-2bfe9ac5d193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
