<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_g1051-email</name>
   <tag></tag>
   <elementGuidId>8aad12b4-b673-4a9b-8910-7aeb331394ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='g1051-email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g1051-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5a5e316-9aae-4cbc-a1f1-d9630bf6cb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bb3bfdcc-184e-4347-a0c4-206341572711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g1051-email</value>
      <webElementGuid>c38a28da-df31-4a30-865f-6490947cfce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g1051-email</value>
      <webElementGuid>a772542a-f9b7-4ae0-8637-73a80c564b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email  grunion-field</value>
      <webElementGuid>a6d1d168-51c0-4fa7-9f4f-15ee44384945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g1051-email&quot;)</value>
      <webElementGuid>3ac2274e-bf4d-42d8-ac9d-cf0f1acf7ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='g1051-email']</value>
      <webElementGuid>c85a00bc-e619-4f01-ab6c-f8e9bfd5af5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form-1051']/form/div[2]/input</value>
      <webElementGuid>034eec2c-7b98-4e75-9364-c5335dcc46be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8c3fc137-4ed6-4fb9-bce5-74779f8b9269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'g1051-email' and @id = 'g1051-email']</value>
      <webElementGuid>9021fd92-f45c-45b9-9d13-7ad5e9fa6a4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
