<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Refresh</name>
   <tag></tag>
   <elementGuidId>b63e31a9-5e63-4f6d-b8e9-bfc329e1d4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Button1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Button1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Refresh&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17fe0b68-dde9-4022-97a6-3b5c4df0fcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Button1</value>
      <webElementGuid>64478a35-1d84-4934-8ed6-f64816cebbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f49f42e-ddf4-45c5-92b9-c3f6f752edca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>50eb92e7-b655-4e3e-8fa6-2dc159e05759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>3396ce0a-f2da-4df5-8c94-e5cd98b43e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>7721d50e-4459-4c2f-b699-87767a417337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Button1&quot;)</value>
      <webElementGuid>4a36acdb-5477-4bdb-90b0-3e69e232b87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Button1']</value>
      <webElementGuid>b69cab07-2307-4156-8366-37fc0bcaf00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[14]/div/button[2]</value>
      <webElementGuid>a6379108-1484-4e55-a842-28c3460da125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::button[1]</value>
      <webElementGuid>e1bd5775-db20-40d7-9abe-a2c53152ec9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::button[2]</value>
      <webElementGuid>014b119e-7ff8-4f04-8837-a0da069c7693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo'])[1]/preceding::button[1]</value>
      <webElementGuid>59a32d5b-04a5-4fc3-af34-7047ab208f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh']/parent::*</value>
      <webElementGuid>ce43bf5b-3ed4-4b30-b7ea-3e11c71cac0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5ad161d5-3fc8-45ee-97f5-905a92b262a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Button1' and @type = 'button' and (text() = 'Refresh' or . = 'Refresh')]</value>
      <webElementGuid>2cbdbdc3-17a9-46c5-b946-4da84a2c4a01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
