<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_firstpassword</name>
   <tag></tag>
   <elementGuidId>06f8ff97-1b59-400a-8db6-cde9c8983407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#firstpassword</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac4f2ec5-2929-4ff0-ab0c-18c5bbbcf0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstpassword</value>
      <webElementGuid>af34a43d-a363-422b-923a-249f77dd3511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7db4668f-3b9a-4c2f-971e-ac973e2a0354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-invalid ng-dirty ng-valid-parse ng-valid-required ng-invalid-minlength</value>
      <webElementGuid>1bbe7590-c8f0-407d-8962-9fec884510d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>0527ddc3-e9f5-45f5-a2b7-d70c5a58b704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>435235e2-806c-43c4-b508-ef8064fb0010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validatepattern(this)</value>
      <webElementGuid>d058db47-f704-4b30-91c8-9604159e3195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstpassword&quot;)</value>
      <webElementGuid>03ea63a2-db6b-4809-85cf-3141c815ee8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstpassword']</value>
      <webElementGuid>82204d3b-bcc0-4f18-9098-1db4fb628fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basicBootstrapForm']/div[12]/div/input</value>
      <webElementGuid>c6033bcc-ad15-4177-bf25-77cd53b4ed8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>80f165b4-8089-484a-958c-5c41ea423325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'firstpassword' and @type = 'password']</value>
      <webElementGuid>46a4ad29-1ef6-4f67-847e-ddd22264c289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
