<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_practice</name>
   <tag></tag>
   <elementGuidId>cc40fd88-03ec-456c-8889-91bafaf88e89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium'])[1]/following::b[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;practice&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>fa81bb2c-bbe4-4ac9-a779-ff1adebd01fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>practice</value>
      <webElementGuid>e872a756-446e-4d32-9a59-1693f96c7e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;d-flex flex-column min-vh-100&quot;]/main[@class=&quot;flex-shrink-0 py-3&quot;]/div[@class=&quot;page-layout&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-9&quot;]/ul[1]/li[1]/b[1]</value>
      <webElementGuid>072e9ef6-bd79-4505-9ca9-b4b92cff1c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium'])[1]/following::b[1]</value>
      <webElementGuid>e82ad9eb-47d3-4434-b174-e68137440c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SuperSecretPassword!'])[1]/preceding::b[1]</value>
      <webElementGuid>c0cb61b9-e309-4c2f-9767-9d3494a28858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='practice']/parent::*</value>
      <webElementGuid>cd539cf6-f278-4b33-867e-43a7cad44890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/b</value>
      <webElementGuid>40a0417c-e27f-407e-81f3-6d400eaa6bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'practice' or . = 'practice')]</value>
      <webElementGuid>8f4a3c6e-fbbc-47a4-97f6-78303d982c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
