<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_et_pb_contact_message_0</name>
   <tag></tag>
   <elementGuidId>ed006bbb-4ccf-4e52-89b5-e8de1b2a95e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#et_pb_contact_message_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='et_pb_contact_message_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#et_pb_contact_message_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9bcab005-daa0-4d54-964f-c80d91a24e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>et_pb_contact_message_0</value>
      <webElementGuid>7814a71a-77a5-4c1f-8608-2193ea86bd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>et_pb_contact_message_0</value>
      <webElementGuid>79c23c03-771b-419d-8136-1319dafc49a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_contact_message input</value>
      <webElementGuid>c62bb7f6-fffb-466e-bd1b-2e74c1cfef0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required_mark</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>034ee8e8-b904-41ac-b8d2-b69b9a967c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field_type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>106488b7-b12c-43a8-9751-35babc225166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original_id</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>ee9822dd-78dc-45eb-ae63-7b0efbe5a042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Message</value>
      <webElementGuid>511c5dc3-123a-4183-8af4-6473623103b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et_pb_contact_message_0&quot;)</value>
      <webElementGuid>9cd35071-3cc5-43c2-9593-99c3d3d8d8f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='et_pb_contact_message_0']</value>
      <webElementGuid>529e31d3-4e3f-4e4c-8297-dbcc6ecd9848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et_pb_contact_form_0']/div[2]/form/p[2]/textarea</value>
      <webElementGuid>d2ae441e-3f70-41d6-8186-3ad870e21297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e72ad8c6-675d-4727-9c23-5577e2023ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'et_pb_contact_message_0' and @id = 'et_pb_contact_message_0' and @placeholder = 'Message']</value>
      <webElementGuid>f6d6ac26-b10a-4b18-a586-182ec89e3471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
