<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_et_pb_contact_message_1</name>
   <tag></tag>
   <elementGuidId>8e71aa98-54d1-4a76-8106-ac061e6c5793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#et_pb_contact_message_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='et_pb_contact_message_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#et_pb_contact_message_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>376ad3bd-dfa0-4a53-a50c-b66aecd28c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>et_pb_contact_message_1</value>
      <webElementGuid>c8fc17bc-8be5-463f-a349-9b154cbaf9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>et_pb_contact_message_1</value>
      <webElementGuid>78978e51-3632-4a88-998d-b09421decc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_contact_message input</value>
      <webElementGuid>3b406f5e-d36d-41bd-9394-36039904b3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required_mark</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9190a89a-fc30-472c-a475-1b51cb6b5a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field_type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59495313-9f89-453d-8bb1-7f85d97df3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original_id</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>934be5e8-17fe-4198-954f-2351a1b7930e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Message</value>
      <webElementGuid>95a63fe5-3aa1-413c-80c6-7b45e1de8905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et_pb_contact_message_1&quot;)</value>
      <webElementGuid>606a9c09-8c9b-47e2-a6f3-cea4e6318fe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='et_pb_contact_message_1']</value>
      <webElementGuid>65729b33-11f8-4912-9a45-40763dcc90ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et_pb_contact_form_1']/div[2]/form/p[2]/textarea</value>
      <webElementGuid>123534ea-abc3-4f8e-9d77-605b2c6adc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/p[2]/textarea</value>
      <webElementGuid>22d9b279-433a-4b0b-8a23-4d3384453dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'et_pb_contact_message_1' and @id = 'et_pb_contact_message_1' and @placeholder = 'Message']</value>
      <webElementGuid>1b1455c2-4d5e-473d-93e5-c355ed18faca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
