<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Invalid email or password</name>
   <tag></tag>
   <elementGuidId>5fad37db-387b-473d-92d4-a422c99c72a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flash']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=paragraph</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1e6ece5a-c785-46f9-82cb-30e7b8da5825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message-text</value>
      <webElementGuid>aa6edc78-0503-4488-9d3c-fc5ea19d88a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid email or password.</value>
      <webElementGuid>a251f5e7-0505-4273-87f8-165c9e6779ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flash&quot;)/div[@class=&quot;col-md-12 message message-alert&quot;]/p[@class=&quot;message-text&quot;]</value>
      <webElementGuid>ee84abf4-348f-474e-8319-76b1f1baa952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flash']/div/p</value>
      <webElementGuid>f3df46ea-0f72-43dc-8e09-31c877ab5a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in a new window'])[1]/following::p[1]</value>
      <webElementGuid>35c9ead0-c0dc-468d-9ca8-1691a46f4de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© Copyright UltimateQA 2024'])[1]/following::p[1]</value>
      <webElementGuid>e43e98bf-6a20-4501-bccd-5548adff4e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>28bfa1d6-bb30-4236-a26b-ef7b15dac5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Invalid email or password.' or . = 'Invalid email or password.')]</value>
      <webElementGuid>ebbb6add-f11a-4e3b-9bae-0075b4b583ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
