<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Automation Testing_g2599-expertise</name>
   <tag></tag>
   <elementGuidId>f083ccbe-e7db-4ede-bb36-24e9f46fde52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='g2599-expertise[]'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Automation Testing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7bc8840-05a9-47e9-adbd-bef1b425d172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a18dabab-f1a6-40aa-beca-a407fe5b7052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g2599-expertise[]</value>
      <webElementGuid>8a538f53-0592-445f-b203-297f6857fd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Automation Testing</value>
      <webElementGuid>3ee1a790-c484-4c5a-a315-d9d623bf5050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-multiple</value>
      <webElementGuid>e9c87edb-a02f-4454-9820-826666ea4971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form-2599&quot;)/form[@class=&quot;contact-form commentsblock&quot;]/div[@class=&quot;grunion-field-wrap grunion-field-checkbox-multiple-wrap&quot;]/label[@class=&quot;grunion-checkbox-multiple-label checkbox-multiple&quot;]/input[@class=&quot;checkbox-multiple&quot;]</value>
      <webElementGuid>66dc9d5c-fddd-4d4a-8ae2-6d547539abfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='g2599-expertise[]'])[2]</value>
      <webElementGuid>57a5b23c-31a8-4ea3-8fd3-a0ca5dc55765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form-2599']/form/div[5]/label[3]/input</value>
      <webElementGuid>b0955cda-e4df-416e-8c48-3f8bf9543180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>1bb79239-6d21-429e-9845-62552b3101c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'g2599-expertise[]']</value>
      <webElementGuid>131ab13a-e658-43e9-bd6e-0bfdada7e3a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
