<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_0-11-33-55-77-1010</name>
   <tag></tag>
   <elementGuidId>49d2fb78-06e1-4c92-8b51-4cb980fbc689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='g2599-experienceinyears']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g2599-experienceinyears</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Experience (In Years)(required)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e64920c0-27d7-4531-9eb6-00de268a0f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g2599-experienceinyears</value>
      <webElementGuid>09c2fb68-b2d4-4694-a7be-cf5a39ca5900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g2599-experienceinyears</value>
      <webElementGuid>75b2bd19-3dcf-40d6-8162-3e02ec0592ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>974c4a9d-2eed-4f16-8fb9-8758a9381a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11c14d26-d778-437c-a8b4-c5c4e4f5f005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		0-1
		1-3
		3-5
		5-7
		7-10
		10+
	</value>
      <webElementGuid>5249a541-fbc6-481c-8646-10cb9a0c10cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g2599-experienceinyears&quot;)</value>
      <webElementGuid>c5bba62d-fd1d-457e-80d1-05cef76f3491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='g2599-experienceinyears']</value>
      <webElementGuid>e80f9bc8-200e-4c59-91b8-3da34514a648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form-2599']/form/div[4]/select</value>
      <webElementGuid>44951b23-a8f9-4a59-8ec3-be45c8203113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(required)'])[3]/following::select[1]</value>
      <webElementGuid>57d11203-8d66-4270-9a11-77a7fc420efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expertise :'])[1]/preceding::select[1]</value>
      <webElementGuid>7f6f6fc3-7339-4dc1-a1bb-01e2dcfcbc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Testing'])[1]/preceding::select[1]</value>
      <webElementGuid>bcb53d6a-7728-43e9-b4d1-3c9eacc9f12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>31905eda-92ea-4393-912f-fcea2c8370d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'g2599-experienceinyears' and @id = 'g2599-experienceinyears' and (text() = '
		0-1
		1-3
		3-5
		5-7
		7-10
		10+
	' or . = '
		0-1
		1-3
		3-5
		5-7
		7-10
		10+
	')]</value>
      <webElementGuid>35a4909a-b13c-4c11-ac85-a436c7fe13cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
