<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(required)_g2599-comment</name>
   <tag></tag>
   <elementGuidId>cf8c52fb-01c0-4fb1-b6e1-da3a2f37ef36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-form-comment-g2599-comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='contact-form-comment-g2599-comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Comment(required)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c7f9e63f-7022-4564-9a77-38934199b6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>g2599-comment</value>
      <webElementGuid>e49aa55c-82a8-4e17-8390-3b2493498756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-form-comment-g2599-comment</value>
      <webElementGuid>88da97ac-a6ef-4434-b470-88ecd5f07330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>efa12461-2231-4fac-966a-a5867a57d856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>30b6ea51-423c-4fda-b032-4a726770486d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77fc3e1f-362f-49ea-ba40-ec05de684f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form-comment-g2599-comment&quot;)</value>
      <webElementGuid>4523f1dd-cd51-4bdc-87f9-021840840922</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='contact-form-comment-g2599-comment']</value>
      <webElementGuid>f6ab7e97-1062-442b-a71d-e85942253403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form-2599']/form/div[7]/textarea</value>
      <webElementGuid>7d29d649-e74f-4783-9a97-bf076f1b3b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2d2ad7fd-b31e-4fdc-93b4-cbdafce5d42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'g2599-comment' and @id = 'contact-form-comment-g2599-comment']</value>
      <webElementGuid>bc90eb6b-be3e-4626-9b4f-751fd3127c70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
