<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cat</name>
   <tag></tag>
   <elementGuidId>bf87067b-b4ff-4c8f-ae3a-7357e4f29fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='catSound()']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Cat' or . = 'Cat')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.custom_btn.btn_hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cat&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62fab4ae-492e-4d2b-ba4f-f534b2712993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_btn btn_hover</value>
      <webElementGuid>bcaf8e85-4173-4f22-89c6-168e2c02dd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>catSound()</value>
      <webElementGuid>416e74b9-de4f-4155-b9af-633b0d232efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cat</value>
      <webElementGuid>25cb7cf0-eb35-4a14-9514-751b9f0ca694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-3145&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;wp-block-columns is-layout-flex wp-container-core-columns-is-layout-2 wp-block-columns-is-layout-flex&quot;]/div[@class=&quot;wp-block-column is-layout-flow wp-block-column-is-layout-flow&quot;]/div[@class=&quot;wp-block-group is-layout-flow wp-block-group-is-layout-flow&quot;]/div[@class=&quot;wp-block-columns is-layout-flex wp-container-core-columns-is-layout-1 wp-block-columns-is-layout-flex&quot;]/div[@class=&quot;wp-block-column is-layout-flow wp-block-column-is-layout-flow&quot;]/button[@class=&quot;custom_btn btn_hover&quot;]</value>
      <webElementGuid>db6dfed1-e2e6-4625-b41f-0600c7112033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='catSound()']</value>
      <webElementGuid>32b49434-d72a-4085-8703-3f7550bdb1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-3145']/div/div[3]/div/div/div/div/button</value>
      <webElementGuid>1225a6ae-3ffd-4c65-b7be-f661b991918d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click Events'])[2]/following::button[1]</value>
      <webElementGuid>e6814adb-6b93-4899-8baa-dec43abc2dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::button[1]</value>
      <webElementGuid>df3f74bb-6d6d-476f-8fcb-b86f54bd997c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dog'])[1]/preceding::button[1]</value>
      <webElementGuid>1a58c2c5-27ca-4079-8df5-cfdab54c612a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>ec9b3888-1b8b-47a1-a609-129c3839b910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cat' or . = 'Cat')]</value>
      <webElementGuid>cf5ef78f-a601-4d65-b7db-c4f84f295770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
