<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1,429</name>
   <tag></tag>
   <elementGuidId>4e5c1456-ce83-40c3-a432-7d4a3054a400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablepress-1']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.column-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;1,429&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>78ba0762-a356-4046-be0e-3fd282198ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>column-3</value>
      <webElementGuid>741c9f59-67b2-4d6e-8fcd-aa19784eb680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1,429</value>
      <webElementGuid>1f69c429-6dc3-4cb1-8cd9-bb055c070bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablepress-1&quot;)/tbody[@class=&quot;row-hover&quot;]/tr[@class=&quot;row-2 even&quot;]/td[@class=&quot;column-3&quot;]</value>
      <webElementGuid>160267ce-864c-42a9-b6af-69debbba5adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablepress-1']/tbody/tr/td[3]</value>
      <webElementGuid>104498b0-4d1c-41a1-bd46-714dd7f39092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/following::td[1]</value>
      <webElementGuid>31048f6d-e388-470c-b3ab-23a647f376d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Population (million)'])[1]/following::td[3]</value>
      <webElementGuid>14619eee-b451-4ef8-b318-1881c73e7aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 25 total entries)'])[1]/preceding::td[1]</value>
      <webElementGuid>4626cd79-d0ab-40c2-bd41-a6726360a23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::td[1]</value>
      <webElementGuid>0309aa91-f9fc-4e22-8307-05b817289110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1,429']/parent::*</value>
      <webElementGuid>bcea9f10-f97b-4b29-9152-0f1e9fb70910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>d7191254-520b-4eac-b725-08f477702535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1,429' or . = '1,429')]</value>
      <webElementGuid>a86b04e2-7547-4ad8-ac86-48a694ae4f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
