<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Click to see more_wp-block-spacer</name>
   <tag></tag>
   <elementGuidId>85040077-5f5a-4cd4-84ee-ea73ac45849a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-1261']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wp-block-spacer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#post-1261 div >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d758ab22-0c15-4571-ad5b-f203dba36bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ac80e8f-1475-4718-943f-eb6de1038aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-spacer</value>
      <webElementGuid>bcbc6f00-7779-47e6-a343-bbf93d436555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1261&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;wp-block-spacer&quot;]</value>
      <webElementGuid>086bbe85-b716-4507-b2c4-26707aadcfa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1261']/div/div[2]</value>
      <webElementGuid>f617bd22-beb0-44da-8c66-c69d2b90da59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div[2]</value>
      <webElementGuid>ae08f83d-ac3b-4cb4-9fc3-02cf4cca6f09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
